### ISSUE TITLE
Restart/Status/kill methods and handle shutdown

### ISSUE THREAD

**Issue by tami5** [DarthUdp/daemonize-me#3]
**Is your feature request related to a problem?

Hey @DarthUdp, amazing work, I've been using daemonize-me for sometime now, and I'd like to have the ability to to start/restart, get status and stop. So that I can create a daemon object and have a set of methods.

**Describe the solution you'd like**

- Start method to accept a function that block the daemon from being killed and be killed if sigterm was received.
- Stop/kill method to kill daemon and execute a user provide cleanup function.
- Restart method to kill the daemon and run start method.
- Status method to pretty print stdout and stdin.

Additionally, it would be awesome if user can provide app name as in clap and description. 

**Describe alternatives you've considered**

I've implemented a semi-independent wrapper for my use case. Here's a gist.

https://gist.github.com/tami5/af81b31307d7cb9e51f31b55e16180ea

**Comment by DarthUdp** [comment]
I will take a closer look at your requests, they all seem reasonable and good improvements overall, I also appreciate the gist

**Comment by xadaemon** [comment]
@tami5 I have added in the master branch a method of changing the name of the process, what do you mean by description in this case?

**Comment by kkharji** [comment]
> @tami5 I have added in the master branch a method of changing the name of the process, what do you mean by description in this case?

Description is few words long string that describe what the service is about. It can be used when call a method to get the service status, e.g. status method that prints service/process name and description, along with stout and stderr. Also, it may be used as well when starting services.

**Comment by xadaemon** [comment]
Will be released with v2.0.0
